# Generated by Django 5.0.4 on 2024-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertimeseries',
            name='max_10m_wind_gust',
            field=models.FloatField(null=True, verbose_name='Max Wind Gust (10m)'),
        ),
        migrations.AlterField(
            model_name='weathertimeseries',
            name='max_screen_air_temp',
            field=models.FloatField(null=True, verbose_name='Max Screen Air Temp'),
        ),
        migrations.AlterField(
            model_name='weathertimeseries',
            name='min_screen_air_temp',
            field=models.FloatField(null=True, verbose_name='Min Screen Air Temp'),
        ),
        migrations.AlterField(
            model_name='weathertimeseries',
            name='total_precip_amount',
            field=models.IntegerField(null=True, verbose_name='Total Precipitation Amount'),
        ),
        migrations.AlterField(
            model_name='weathertimeseries',
            name='total_snow_amount',
            field=models.IntegerField(null=True, verbose_name='Total Snow Amount'),
        ),
    ]
