# Generated by Django 5.0.4 on 2024-04-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRunDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_run_date', models.DateTimeField(verbose_name='Model Run Date')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('screen_temperature', models.FloatField(verbose_name='Screen Temperature')),
                ('max_screen_air_temp', models.FloatField(null=True, verbose_name='Max Screen Air Temp')),
                ('min_screen_air_temp', models.FloatField(null=True, verbose_name='Min Screen Air Temp')),
                ('screen_dew_point_temperature', models.FloatField(verbose_name='Screen Dew Point Temperature')),
                ('feels_like_temperature', models.FloatField(verbose_name='Feels Like Temperature')),
                ('wind_speed_10m', models.FloatField(verbose_name='Wind Speed (10m)')),
                ('wind_direction_from_10m', models.IntegerField(verbose_name='Wind Direction (10m)')),
                ('wind_gust_speed_10m', models.FloatField(verbose_name='Wind Gust Speed (10m)')),
                ('max_10m_wind_gust', models.FloatField(null=True, verbose_name='Max Wind Gust (10m)')),
                ('visibility', models.IntegerField()),
                ('screen_relative_humidity', models.FloatField(verbose_name='Screen Relative Humidity')),
                ('mslp', models.IntegerField()),
                ('uv_index', models.IntegerField(verbose_name='UV Index')),
                ('significant_weather_code', models.IntegerField(verbose_name='Significant Weather Code')),
                ('precipitation_rate', models.IntegerField(verbose_name='Precipitation Rate')),
                ('total_precip_amount', models.IntegerField(null=True, verbose_name='Total Precipitation Amount')),
                ('total_snow_amount', models.IntegerField(null=True, verbose_name='Total Snow Amount')),
                ('prob_of_precipitation', models.IntegerField(verbose_name='Probability of Precipitation')),
                ('model_run_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='weather_forecast.modelrundate')),
            ],
        ),
    ]
